import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import styles from "../styles/Home.module.css";
import { Sidebar } from "../components/Sidebar/Sidebar";
import { Header } from "../components/Header/Header";
import { Footer } from "../components/Footer/Footer";
import { useState, useEffect } from "react";
import { theme } from "../constants";
import {
  faReact,
  faJs,
  faCss3Alt,
  faHtml5,
} from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { appear } from "../constants";

const MainContainer = styled.div`
  background-color: ${theme.colors.secondary};
  display: flex;
  height: 100vh;
  overflow-x: hidden;
  font-family: "Plus Jakarta Sans";
  @media (max-width: 800px) {
    width: calc(100vw + 1px);
    transform: translateX(-1px);
  }
`;

const MainContent = styled.div`
  animation: ${appear} 0.3s linear forwards;
  width: calc(100vw - 81px);
  height: max-content;
  @media (max-width: 800px) {
    width: 100vw;
  }
`;

const Content = styled.div`
  width: calc(100vw - 81px);
  & > div {
    padding: 30px;
    @media (max-width: 800px) {
      padding: 25px 25px 40px 25px;
      width: 100%;
    }
  }
  border-bottom: 1px solid ${theme.colors.primary};
  @media (max-width: 800px) {
    width: 100vw;
    flex-direction: column;
    & > span img {
      object-position: top !important;
    }
    & > div {
      border-left: 0px solid ${theme.colors.primary};
    }
  }
`;

const Title = styled.div`
  font-size: 65px;
  line-height: 65px;
  display: flex;
  flex-direction: column;
  font-family: "Plus Jakarta Sans";
  font-weight: 800;
  color: ${theme.colors.primary};
  margin-bottom: 60px;
  text-align: left;
  & > span {
    padding: 0;
    @media (max-width: 800px) {
      font-size: 40px;
      line-height: 40px;
    }
  }
  & > span:nth-child(3) {
    color: ${theme.colors.secondary};
    text-shadow: 4px 4px 13px ${theme.colors.shadow};
  }
  @media (max-width: 800px) {
    margin-bottom: 40px;
  }
`;

const Description = styled.div`
  color: ${theme.colors.primary};
  font-size: 17px;
  line-height: 22px;
  max-width: 500px;
  @media (max-width: 800px) {
    font-size: 16px;
  }
`;

const HighLight = styled.span`
  border-bottom: 1px solid ${theme.colors.shadowLight};
  color: ${theme.colors.shadow};
  margin: 0 4px;
`;

const ViewMore = styled.div`
  margin-top: 40px;
  & a {
    color: ${theme.colors.primary};
    font-size: 18px;
    cursor: pointer;
    border-bottom: 2px solid ${theme.colors.primary};
    padding-bottom: 5px;
    text-transform: uppercase;
    @media (max-width: 800px) {
      font-size: 16px;
    }
  }
`;

const ProjectsContainer = styled.div`
  font-family: "Plus Jakarta Sans";
  padding: 25px 100px 50px !important;
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-gap: 50px;
  @media (max-width: 800px) {
    padding: 0px 25px 50px !important;
    grid-template-columns: 1fr;
    grid-gap: 40px;
  }
`;

const ProjectCard = styled.div`
  border: 1px solid ${theme.colors.primary};
  & > div {
    padding: 30px;
  }
  & > div:first-child {
    border-bottom: 1px solid ${theme.colors.shadow};
  }
  & > div:nth-child(2) {
    padding-bottom: 0;
  }
  & > div:nth-child(3) {
    display: flex;
    flex-wrap: wrap;
  }
  @media (max-width: 800px) {
    & > div {
      padding: 20px;
    }
  }
`;

const ProjectTitle = styled.div`
  width: max-content;
  font-size: 19px;
  font-weight: 600;
  color: ${theme.colors.primary};
  &:hover {
    color: ${theme.colors.shadow};
  }
`;

const ProjectDescription = styled.div`
  color: ${theme.colors.primary};
  font-size: 16px;
  @media (max-width: 800px) {
    font-size: 15px;
  }
`;

const ProjectTags = styled.div`
  background-color: ${theme.colors.secondary};
  color: ${theme.colors.shadow};
  font-size: 16px;
  border: 1px solid ${theme.colors.shadow};
  padding: 6px;
  margin-right: 10px;
  @media (max-width: 800px) {
    font-size: 16px;
  }
  @media (max-width: 800px) {
    font-size: 15px;
    margin-right: 7px;
  }
`;

export default function Projects() {
  const [isSSR, setIsSSR] = useState(true);

  useEffect(() => {
    setIsSSR(false);
  }, []);

  return (
    !isSSR && (
      <div>
        <Head>
          <title>Projects - Nam Nguyen</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MainContainer>
          <Sidebar />
          <MainContent>
            <Header />
            <>
              <Content>
                <div>
                  <Title>
                    <span>Projects</span>
                  </Title>
                  <Description>
                    <p>
                      Some projects for courses, training and my self-studying.
                    </p>
                  </Description>
                  <ViewMore>
                    <a
                      href="https://github.com/nguyend-nam/?tab=repositories"
                      rel="noreferrer"
                      target="_blank"
                    >
                      View more on GitHub{" "}
                      <span
                        style={{ fontSize: "14px", fontWeight: "900" }}
                        className="material-symbols-outlined"
                      >
                        arrow_right_alt
                      </span>
                    </a>
                  </ViewMore>
                </div>
                <ProjectsContainer>
                  <ProjectCard>
                    <div>
                      <ProjectTitle>
                        <a
                          href="https://github.com/nguyend-nam/nextjs-calendar"
                          rel="noreferrer"
                          target="_blank"
                        >
                          Next.JS calendar page UI
                        </a>
                      </ProjectTitle>
                    </div>
                    <ProjectDescription>
                      Calendar section for dashboard UI built with{" "}
                      <HighLight>
                        <a
                          href="https://github.com/dwarvesf/nextjs-boilerplate"
                          rel="noreferrer"
                          target="_blank"
                        >
                          dwarvesf&rsquo;s NextJS boilerplate
                          <span
                            className="material-symbols-outlined"
                            style={{ fontSize: "14px", fontWeight: "600" }}
                          >
                            arrow_outward
                          </span>
                        </a>
                      </HighLight>
                      .
                    </ProjectDescription>
                    <div>
                      <ProjectTags>Next.JS</ProjectTags>
                      <ProjectTags>TypeScript</ProjectTags>
                      <ProjectTags>TailwindCSS</ProjectTags>
                    </div>
                  </ProjectCard>
                  <ProjectCard>
                    <div>
                      <ProjectTitle>
                        <a
                          href="https://github.com/nguyend-nam/google-fonts-clone/tree/feat/localstorage"
                          rel="noreferrer"
                          target="_blank"
                        >
                          Google Fonts app clone
                        </a>
                      </ProjectTitle>
                    </div>
                    <ProjectDescription>
                      <HighLight>
                        <a
                          href="https://fonts.google.com"
                          rel="noreferrer"
                          target="_blank"
                        >
                          Google Fonts app
                          <span
                            className="material-symbols-outlined"
                            style={{ fontSize: "14px", fontWeight: "600" }}
                          >
                            arrow_outward
                          </span>
                        </a>
                      </HighLight>{" "}
                      clone with fully UI-UX implemented.
                    </ProjectDescription>
                    <div>
                      <ProjectTags>Next.JS</ProjectTags>
                      <ProjectTags>TypeScript</ProjectTags>
                      <ProjectTags>TailwindCSS</ProjectTags>
                    </div>
                  </ProjectCard>
                  <ProjectCard>
                    <div>
                      <ProjectTitle>
                        <a
                          href="https://github.com/DecSP/cses-downloader"
                          rel="noreferrer"
                          target="_blank"
                        >
                          CSES Downloader
                        </a>
                      </ProjectTitle>
                    </div>
                    <ProjectDescription>
                      <HighLight>
                        <a
                          href="https://cses.fi/"
                          rel="noreferrer"
                          target="_blank"
                        >
                          CSES
                          <span
                            className="material-symbols-outlined"
                            style={{ fontSize: "14px", fontWeight: "600" }}
                          >
                            arrow_outward
                          </span>
                        </a>
                      </HighLight>{" "}
                      problemset solutions downloader + packager with
                      user-friendly web interface.
                    </ProjectDescription>
                    <div>
                      <ProjectTags>JavaScript</ProjectTags>
                      <ProjectTags>HTML</ProjectTags>
                      <ProjectTags>CSS</ProjectTags>
                      <ProjectTags>Python</ProjectTags>
                    </div>
                  </ProjectCard>
                </ProjectsContainer>
              </Content>
            </>
            <Footer />
          </MainContent>
        </MainContainer>
      </div>
    )
  );
}
